server:
  port: 8000
spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    url:  jdbc:postgresql://localhost:5432/myApp
    username: postgres
    password: 123
